[api]
port = 54321
schemas = ["public", "auth", "storage"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
double_confirm_changes = false

[storage]
enabled = true

[inbucket]
enabled = true
port = 54324
