export enum ErrorCode {
  // Authentication errors
  AUTH_ERROR = 'AUTH_ERROR',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',

  // Database errors
  DB_ERROR = 'DB_ERROR',
  DB_QUERY_ERROR = 'DB_QUERY_ERROR',
  DB_CONNECTION_ERROR = 'DB_CONNECTION_ERROR',
  DB_CONSTRAINT_ERROR = 'DB_CONSTRAINT_ERROR',
  DB_VALIDATION_ERROR = 'DB_VALIDATION_ERROR',

  // API errors
  API_ERROR = 'API_ERROR',
  API_REQUEST_ERROR = 'API_REQUEST_ERROR',
  API_RESPONSE_ERROR = 'API_RESPONSE_ERROR',
  API_VALIDATION_ERROR = 'API_VALIDATION_ERROR',

  // Business logic errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_STATE = 'INVALID_STATE',
  CONFLICT = 'CONFLICT',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',

  // Schedule-specific errors
  SCHEDULE_CONFLICT = 'SCHEDULE_CONFLICT',
  INSUFFICIENT_STAFF = 'INSUFFICIENT_STAFF',
  INVALID_SHIFT_PATTERN = 'INVALID_SHIFT_PATTERN',
  OVERTIME_LIMIT_EXCEEDED = 'OVERTIME_LIMIT_EXCEEDED',

  // Generic errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  OPERATION_FAILED = 'OPERATION_FAILED',
  SERVER_ERROR = 'SERVER_ERROR'
} 